[package]
name = "backend-portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
bb8 = "0.9.0"
bb8-postgres = "0.9.0"
tokio = { version = "1.46.0", features = ["full"] }
tokio-postgres = "0.7.13"
