version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    container_name: portfolio_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://portfolio_user:portfolio_password@postgres:5432/portfolio_db
      RUST_LOG: debug
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - target:/usr/src/app/target

volumes:
  postgres_data:
  target:
